title: ðŸ“ŠðŸŽðŸ¥³
author: St. Nich ðŸ
description: > # this means to ignore newlines until "baseurl:"
  Delivering gifts of data. 
theme: minima
baseurl: "/github-pages-with-jekyll"
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# social links
github_username:  st-nich # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
